# 1. 向量化和广播

向量化和广播这两个概念是 numpy 内部实现的基础。有了向量化，编写代码时无需使用显式循环。这些循环实际上不能省略，只不过是在内部实现，被代码中的其他结构代替。向量化的应用使得代码更简洁，可读性更强，也可以说使用了向量化方法的代码看上去更“Pythonic”。

广播（Broadcasting）机制描述了 numpy 如何在算术运算期间处理具有不同形状的数组，让较小的数组在较大的数组上“广播”，以便它们具有兼容的形状。并不是所有的维度都要彼此兼容才符合广播机制的要求，但它们必须满足一定的条件。

若两个数组的各维度兼容，也就是两个数组的每一维等长，或其中一个数组为 一维，那么广播机制就适用。如果这两个条件不满足，numpy就会抛出异常，说两个数组不兼容。

总结来说，广播的规则有三个：

- 如果两个数组的维度数dim不相同，那么小维度数组的形状将会在左边补1。
- 如果shape维度不匹配，但是有维度是1，那么可以扩展维度是1的维度匹配另一个数组；
- 如果shape维度不匹配，但是没有任何一个维度是1，则匹配引发错误；

In [2]:
import numpy as np

x = np.arange(4)
y = np.ones((3, 4))
print(x.shape)  
print(y.shape) 
print(x)
print(y)

print((x + y).shape)
print(x + y)

(4,)
(3, 4)
[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [3]:
x = np.arange(4).reshape(4, 1)
y = np.ones(5)

print(x.shape)  
print(y.shape) 

print(x)
print(y)

print((x + y).shape) 
print(x + y)

(4, 1)
(5,)
[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


# 2. 数学函数

## 2.1 算数运算
在 numpy 中对以上函数进行了运算符的重载，且运算符为 元素级。也就是说，它们只用于位置相同的元素之间，所得到的运算结果组成一个新的数组。

- numpy.add: numpy.add(x1, x2, *args, **kwargs) Add arguments element-wise.   
- numpy.subtract: Subtract arguments element-wise.
- numpy.multiply: Multiply arguments element-wise.
- numpy.divide: Returns a true division of the inputs, element-wise.
- numpy.floor_divide: Return the largest integer smaller or equal to the division of the inputs.
- numpy.power: First array elements raised to powers from second array, element-wise.
- numpy.sqrt: Return the non-negative square-root of an array, element-wise.
- numpy.square: Return the element-wise square of the input.

In [4]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = x + 1
print(y)
print(np.add(x, 1))

y = x - 1
print(y)
print(np.subtract(x, 1))


y = x * 2
print(y)
print(np.multiply(x, 2))


y = x / 2
print(y)
print(np.divide(x, 2))


y = x // 2
print(y)
print(np.floor_divide(x, 2))


y = x ** 2
print(y)
print(np.power(x, 2))

[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[0 1 1 2 2 3 3 4]
[0 1 1 2 2 3 3 4]
[ 1  4  9 16 25 36 49 64]
[ 1  4  9 16 25 36 49 64]


In [5]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = x + 1
print(y)
print(np.add(x, 1))

y = x - 1
print(y)
print(np.subtract(x, 1))

y = x * 2
print(y)
print(np.multiply(x, 2))


y = x / 2
print(y)
print(np.divide(x, 2))


y = x // 2
print(y)
print(np.floor_divide(x, 2))

y = x ** 2
print(y)
print(np.power(x, 2))

[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]
 [32 33 34 35 36]]
[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]
 [32 33 34 35 36]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
[[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]
 [13.  13.5 14.  14.5 15. ]
 [15.5 16.  16.5 17.  17.5]]
[[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]
 [13.  13.5 14.  14.5 15. ]
 [15.5 16.  16.5 17.  17.5]]
[[ 5  6  6  7  7]
 [ 8  8  9  9 10]
 [10 11 11 12 12]
 [13 13 14 14 15]
 [15 16 16 17 17]]
[[ 5  6  6  7  7]
 [ 8  8  9  9 10]
 [10 11 11 12 12]
 [13 13 14 14 15]
 [15 16 1

In [6]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

y = np.arange(1, 6)
print(y)

z = x + y
print(z)
print(np.add(x, y))

z = x - y
print(z)
print(np.subtract(x, y))

z = x * y
print(z)
print(np.multiply(x, y))

z = x / y
print(z)
print(np.divide(x, y))

z = x // y
print(z)
print(np.floor_divide(x, y))

z = x ** np.full([1, 5], 2)
print(z)
print(np.power(x, np.full([5, 5], 2)))

[1 2 3 4 5]
[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]
[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]
[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]
[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]
[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]
[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]
[[11.          6.          4.33333333  3.5         3.        ]
 [16.          8.5         6.          4.75        4.        ]
 [21.         11.          7.66666667  6.          5.        ]
 [26.         13.5         9.33333333  7.25        6.        ]
 [31.         16.         11.          8.5         7.        ]]
[[11.          6.          4.33333333  3.5         3.        ]
 [16.        

In [7]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

y = np.arange(1, 26).reshape([5, 5])
print(y)

z = x + y
print(z)
print(np.add(x, y))

z = x - y
print(z)
print(np.subtract(x, y))

z = x * y
print(z)
print(np.multiply(x, y))

z = x / y
print(z)
print(np.divide(x, y))

z = x // y
print(z)
print(np.floor_divide(x, y))

z = x ** np.full([5, 5], 2)
print(z)
print(np.power(x, np.full([5, 5], 2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
[[12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]
 [231 264 299 336 375]
 [416 459 504 551 600]
 [651 704 759 816 875]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]
 [231 264 299 336 375]
 [416 459 504 551 600]
 [651 704 759 816 875]]
[[11.          6.          4.33333333  3.5         3.        ]
 [ 2.66666667  2.42857143  2.25        2.11111111  2.        ]
 [ 1.90909091  1.83333333  1.76923077  1.71428571  1.66666667]
 [ 1.625       1.58823529  1.55555556  1.52631579  1.5       ]
 [ 1.47619048  1.45454545  1.43478261  1.41666667  1.4       

In [8]:
x = np.arange(1, 5)
print(x)

y = np.sqrt(x)
print(y)

print(np.power(x, 0.5))


y = np.square(x)
print(y)

print(np.power(x, 2))


[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]
[ 1  4  9 16]


# 3. 三角函数

- numpy.sin: numpy.sin(x, *args, **kwargs) Trigonometric sine, element-wise.
- numpy.cos: numpy.cos(x, *args, **kwargs) Cosine element-wise.
- numpy.tan: numpy.tan(x, *args, **kwargs) Compute tangent element-wise.
- numpy.arcsin: numpy.arcsin(x, *args, **kwargs) Inverse sine, element-wise.
- numpy.arccos: numpy.arccos(x, *args, **kwargs) Trigonometric inverse cosine, element-wise.
- numpy.arctan: numpy.arctan(x, *args, **kwargs) Trigonometric inverse tangent, element-wise.

通用函数（universal function）通常叫作ufunc，它对数组中的各个元素逐一进行操作。这表明，通用函数分别处理输入数组的每个元素，生成的结果组成一个新的输出数组。输出数组的大小跟输入数组相同。

三角函数等很多数学运算符合通用函数的定义，例如，计算平方根的sqrt()函数、用来取对数的log()函数和求正弦值的sin()函数。



In [9]:
x = np.linspace(start=0, stop=np.pi / 2, num=10)
print(x)

y = np.sin(x)
print(y)

z = np.arcsin(y)
print(z)

y = np.cos(x)
print(y)

z = np.arccos(y)
print(z)

y = np.tan(x)
print(y)

z = np.arctan(y)
print(z)

[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.        ]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[1.00000000e+00 9.84807753e-01 9.39692621e-01 8.66025404e-01
 7.66044443e-01 6.42787610e-01 5.00000000e-01 3.42020143e-01
 1.73648178e-01 6.12323400e-17]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[0.00000000e+00 1.76326981e-01 3.63970234e-01 5.77350269e-01
 8.39099631e-01 1.19175359e+00 1.73205081e+00 2.74747742e+00
 5.67128182e+00 1.63312394e+16]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]


# 4.指数和对数

- numpy.exp: Calculate the exponential of all elements in the input array.
- numpy.log: numpy.log(x, *args, **kwargs) Natural logarithm, element-wise.
- numpy.exp2: numpy.exp2(x, *args, **kwargs) Calculate 2**p for all p in the input array.
- numpy.log2: numpy.log2(x, *args, **kwargs) Base-2 logarithm of x.
- numpy.log10: numpy.log10(x, *args, **kwargs) Return the base 10 logarithm of the input array, element-wise.

In [10]:
x = np.arange(1, 5)
print(x)

y = np.exp(x)
print(y)

z = np.log(y)
print(z)


[1 2 3 4]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1. 2. 3. 4.]


# 5. 加法函数和减法函数

numpy.sum
- numpy.sum(a[, axis=None, dtype=None, out=None, …]) Sum of array elements over a given axis.

通过不同的 axis，numpy 会沿着不同的方向进行操作：如果不设置，那么对所有的元素操作；如果axis=0，则沿着纵轴进行操作；axis=1，则沿着横轴进行操作。但这只是简单的二位数组，如果是多维的呢？可以总结为一句话：设axis=i，则 numpy 沿着第i个下标变化的方向进行操作。

numpy.cumsum
- numpy.cumsum(a, axis=None, dtype=None, out=None) Return the cumulative sum of the elements along a given axis.

聚合函数 是指对一组值（比如一个数组）进行操作，返回一个单一值作为结果的函数。因而，求数组所有元素之和的函数就是聚合函数。ndarray类实现了多个这样的函数。

In [12]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.sum(x)
print(y) 

y = np.sum(x, axis=0)
print(y) 

y = np.sum(x, axis=1)

575
[105 110 115 120 125]


In [13]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.cumsum(x)
print(y)

y = np.cumsum(x, axis=0)
print(y)

y = np.cumsum(x, axis=1)
print(y)

[ 11  23  36  50  65  81  98 116 135 155 176 198 221 245 270 296 323 351
 380 410 441 473 506 540 575]
[[ 11  12  13  14  15]
 [ 27  29  31  33  35]
 [ 48  51  54  57  60]
 [ 74  78  82  86  90]
 [105 110 115 120 125]]
[[ 11  23  36  50  65]
 [ 16  33  51  70  90]
 [ 21  43  66  90 115]
 [ 26  53  81 110 140]
 [ 31  63  96 130 165]]


numpy.prod 乘积
- numpy.prod(a[, axis=None, dtype=None, out=None, …]) Return the product of array elements over a given axis.

numpy.cumprod 累乘
- numpy.cumprod(a, axis=None, dtype=None, out=None) Return the cumulative product of elements along a given axis.

In [14]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.prod(x)
print(y) 

y = np.prod(x, axis=0)
print(y)


y = np.prod(x, axis=1)
print(y)

3712525927079477248
[2978976 3877632 4972968 6294624 7875000]
[  360360  1860480  6375600 17100720 38955840]


In [15]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.cumprod(x)
print(y)

y = np.cumprod(x, axis=0)
print(y)

y = np.cumprod(x, axis=1)
print(y)

[                  11                  132                 1716
                24024               360360              5765760
             98017920           1764322560          33522128640
         670442572800       14079294028800      309744468633600
     7124122778572800   170978946685747200  4274473667143680000
   455850903478370304 -6138769679793553408 -5864854370833530880
 -4060080090786430976  7324805792373932032  5708050679077273600
 -1809819006622760960 -4383794997422456832 -1475077322687119360
  3712525927079477248]
[[     11      12      13      14      15]
 [    176     204     234     266     300]
 [   3696    4488    5382    6384    7500]
 [  96096  121176  150696  185136  225000]
 [2978976 3877632 4972968 6294624 7875000]]
[[      11      132     1716    24024   360360]
 [      16      272     4896    93024  1860480]
 [      21      462    10626   255024  6375600]
 [      26      702    19656   570024 17100720]
 [      31      992    32736  1113024 38955840]]


numpy.diff 差值
- numpy.diff(a, n=1, axis=-1, prepend=np._NoValue, append=np._NoValue) Calculate the n-th discrete difference along the given axis.
- a：输入矩阵
- n：可选，代表要执行几次差值
- axis：默认是最后一个

The first difference is given by out[i] = a[i+1] - a[i] along the given axis, higher differences are calculated by using diff recursively.

In [17]:
A = np.arange(2, 14).reshape((3, 4))
A[1, 1] = 8
print(A)

print(np.diff(A))

print(np.diff(A, axis=0))

[[ 2  3  4  5]
 [ 6  8  8  9]
 [10 11 12 13]]
[[1 1 1]
 [2 0 1]
 [1 1 1]]
[[4 5 4 4]
 [4 3 4 4]]


# 6. 四舍五入

numpy.around 舍入
- numpy.around(a, decimals=0, out=None) Evenly round to the given number of decimals.

In [18]:
x = np.random.rand(3, 3) * 10
print(x)

y = np.around(x)
print(y)

y = np.around(x, decimals=2)
print(y)

[[6.06552541 1.55718747 8.17304071]
 [3.8687886  4.59680006 8.86885702]
 [6.11030188 3.17894249 7.27215113]]
[[6. 2. 8.]
 [4. 5. 9.]
 [6. 3. 7.]]
[[6.07 1.56 8.17]
 [3.87 4.6  8.87]
 [6.11 3.18 7.27]]


- numpy.ceil 上限： numpy.ceil(x, *args, **kwargs) Return the ceiling of the input, element-wise.
- numpy.floor 下限： numpy.floor(x, *args, **kwargs) Return the floor of the input, element-wise.

In [19]:
x = np.random.rand(3, 3) * 10
print(x)

y = np.ceil(x)
print(y)


y = np.floor(x)
print(y)

[[1.71846312 1.5038138  4.36334218]
 [1.35113788 9.69829411 2.95323248]
 [3.1237811  2.62926868 5.77900613]]
[[ 2.  2.  5.]
 [ 2. 10.  3.]
 [ 4.  3.  6.]]
[[1. 1. 4.]
 [1. 9. 2.]
 [3. 2. 5.]]
