# 1. 常量

## 1.1 numpy.nan

- 定义：表示非数值 （not a number), 表示一个不确定的数, 所以两个nan不相等
- nan = Nan = NAN 
- 用numpy.isnan(x, *args, **kwargs) 来判断是否有Nan，返回真假
[关于args和kwargs](lhttps://blog.csdn.net/weixin_37720172/article/details/78255177])

### 例  (判断是否数组中含有nan）

In [16]:
import numpy as np

a = np.array([1, 1, 8, np.nan, 10])
print(a)

b = np.isnan(a)
print(b)

[ 1.  1.  8. nan 10.]
[False False False  True False]


In [19]:
#count_nonzero()方法是求一个数组中非零元素的个数
np.count_nonzero(b)

1

## 1.2 numpy.inf

- 定义：表示正无穷大，返回浮点
- Inf = inf = infty = Infinity = PINF

## 1.3 numpy.NINF

- 定义：表示负无穷大，返回浮点

    isinf : 显示哪些元素为正或负无穷大
    isposinf : 显示哪些元素是正无穷大
    isneginf : 显示哪些元素为负无穷大
    isfinite : 显示哪些元素是有限的（不是非数字，正无穷大和负无穷大中的一个）

## 1.4 numpy.pi

- 定义：表示圆周率，pi = 3.1415926535897932384626433...

## 1.5 numpy.e

- 定义：表示自然常数

# 2. 数据类型

- Python 原生的数据类型相对较少， bool、int、float、str，为了加以区分 numpy 在这些类型名称末尾都加了“_”

## 2.1 创建数据类型

- numpy 的数值类型实际上是 dtype 对象的实例

In [24]:
#如何查看数据类型
x = np.dtype('f8')
print(x.type)

<class 'numpy.float64'>


In [26]:
#如何查看数据信息
y = np.finfo(np.float64)
print(y.min, y.max)

-1.7976931348623157e+308 1.7976931348623157e+308


# 3. 时间日期和时间增量

## 3.1 datetime64 基础

- 在 numpy 中，我们很方便的将字符串转换成时间日期类型 datetime64（datetime 已被 python 包含的日期时间库所占用）
- 从字符串创建 datetime64 类型时，默认情况下，numpy 会根据字符串自动选择对应的单位

### 例

In [33]:
m = np.datetime64('2020-10-20')
print(m, m.dtype)

n = np.datetime64('2020-10')
print(n, n.dtype)

#从字符串创建 datetime64 类型时，可以强制指定使用的单位。

o = np.datetime64('2020-10', 'Y')
print(o, o.dtype)

2020-10-20 datetime64[D]
2020-10 datetime64[M]
2020 datetime64[Y]


In [34]:
#从字符串创建 datetime64 数组时，如果单位不统一，则一律转化成其中最小的单位。

p = np.array(['2020-03', '2020-03-08', '2020-03-08 20:00'], dtype='datetime64')
print(p, p.dtype)

['2020-03-01T00:00' '2020-03-08T00:00' '2020-03-08T20:00'] datetime64[m]


In [36]:
#使用arange()创建 datetime64 数组，用于生成日期范围。

q = np.arange('2020-08-01', '2020-08-10', dtype=np.datetime64)
print(q)
print(q.dtype)  

['2020-08-01' '2020-08-02' '2020-08-03' '2020-08-04' '2020-08-05'
 '2020-08-06' '2020-08-07' '2020-08-08' '2020-08-09']
datetime64[D]


## 3.1 datetime64 和 timedelta64 运算

- 定义：timedelta64 表示两个 datetime64 之间的差。timedelta64 也是带单位的，并且和相减运算中的两个 datetime64 中的较小的单位保持一致。

### 例

In [41]:
e = np.datetime64('2020-03-08') - np.datetime64('202-03-07 08:00')
print(e, e.dtype)

f = np.datetime64('2020-03-08') - np.datetime64('2020-03-07 23:00', 'D')
print(f, f.dtype)

g = np.datetime64('2020-06-15 00:00') + np.timedelta64(12, 'h')
print(g, g.dtype) 

#生成 timedelta64时，要注意年（'Y'）和月（'M'）这两个单位无法和其它单位进行运算（一年有几天？一个月有几个小时？这些都是不确定的）
h = np.timedelta64(1, 'Y')
i = np.timedelta64(h, 'M')
print(h)  
print(i) 

#print(np.timedelta64(h, 'D'))
# TypeError: Cannot cast NumPy timedelta64 scalar from metadata [Y] to [D] according to the rule 'same_kind'


956178240 minutes timedelta64[m]
1 days timedelta64[D]
2020-06-15T12:00 datetime64[m]
1 years
12 months


In [42]:
#timedelta64 的运算
j = np.timedelta64(1, 'Y')
k = np.timedelta64(6, 'M')
print(j)  # 1 years
print(k)  # 6 months
print(j + k)  # 18 months

1 years
6 months
18 months


# 4. 数组的创建

## 4.1 通过array( )函数进行创建

- numpy 提供的最重要的数据结构是ndarray，它是 python 中list的扩展。

### 例

In [46]:
#创建一维数组
array1 = np.array([0, 1, 2, 3, 4])
print(array1, type(array1), array1.dtype)

#创建二维数组
array2 = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(array2, type(array2))

[0 1 2 3 4] <class 'numpy.ndarray'> int64
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] <class 'numpy.ndarray'>


In [ ]:
#array()和asarray()都可以将结构数据转化为 ndarray，
#但是array()和asarray()主要区别就是当数据源是ndarray 时，array()仍然会 copy 出一个副本，占用新的内存，
#但不改变 dtype 时 asarray()不会。

## 4.2 通过fromfunction( )函数进行创建

In [48]:
array3 = np.fromfunction(lambda i,j : 10*i + j, (5, 4), dtype=int)
print(array3)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


## 4.3 依据 ones 和 zeros 填充方式

- zeros()函数：返回给定形状和类型的零数组。
- zeros_like()函数：返回与给定数组形状和类型相同的零数组。
- ones()函数：返回给定形状和类型的1数组。
- ones_like()函数：返回与给定数组形状和类型相同的1数组。

In [50]:
array4 = np.zeros(5)
print(array4) 

array5 = np.zeros([2,3])
print(array5)

array6 = np.ones(5)
print(array6)

array7 = np.array([[1, 2, 3], [4, 5, 6]])
array8 = np.ones_like(array7)
#ones_like()函数：返回与给定数组形状和类型相同的1数组。
print(array8)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


## 4.4 空数组

- empty()函数：返回一个空数组，数组元素为随机数。
- empty_like函数：返回与给定数组具有相同形状和类型的新数组。

In [ ]:
#np.empty(5)
# [1.95821574e-306 1.60219035e-306 1.37961506e-306, 9.34609790e-307 1.24610383e-306]

#np.empty((3, 2))
# [[1.60220393e-306 9.34587382e-307]
#  [8.45599367e-307 7.56598449e-307]
#  [1.33509389e-306 3.59412896e-317]]

## 4.5 单位数组

- eye()函数：返回一个对角线上为1，其它地方为零的单位数组。
- identity()函数：返回一个方的单位数组。

In [51]:
#x = np.eye(4)
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

#x = np.eye(2, 3)
# [[1. 0. 0.]
#  [0. 1. 0.]]

#x = np.identity(4)
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

## 4.6 常数数组

- full()函数：返回一个常数数组。
- full_like()函数：返回与给定数组具有相同形状和类型的常数数组。

In [ ]:
#x = np.full((2, 7), 7)
# [[7 7 7 7 7 7 7]
#  [7 7 7 7 7 7 7]]

#x = np.array([[1, 2, 3], [4, 5, 6]])
#y = np.full_like(x, 7)
# [[7 7 7]
#  [7 7 7]]

## 4.7 利用数值范围来创建ndarray

- arange()函数：返回给定间隔内的均匀间隔的值。
- linspace()函数：返回指定间隔内的等间隔数字。
- logspace()函数：返回数以对数刻度均匀分布。
- numpy.random.rand() 返回一个由[0,1) 内的随机数组成的数组。

In [ ]:
#x = np.arange(5)
#[0 1 2 3 4]

#x = np.arange(3, 7, 2)
#[3 5]

#x = np.linspace(start=0, stop=2, num=9) 
#[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

#x = np.logspace(0, 1, 5)
#print(np.around(x, 2))
# [ 1.    1.78  3.16  5.62 10.  ] 

#x = np.random.random(5)
# [0.41768753 0.16315577 0.80167915 0.99690199 0.11812291]

#x = np.random.random([2, 3])
# [[0.41151858 0.93785153 0.57031309]
#  [0.13482333 0.20583516 0.45429181]]


## 4.8 结构数组的创建

In [64]:
personType = np.dtype({
    'names': ['name', 'age', 'weight'],
    'formats': ['U30', 'i8', 'f8']})
personType

dtype([('name', '<U30'), ('age', '<i8'), ('weight', '<f8')])

In [65]:
print(personType)

[('name', '<U30'), ('age', '<i8'), ('weight', '<f8')]


In [62]:
personType[0].type

numpy.str_

In [61]:
type(personType)

numpy.dtype

In [67]:
aa = np.array([('Liming', 24, 63.9), ('Mike', 15, 67.), ('Jan', 34, 45.8)],
             dtype=personType)
aa
print(aa, type(aa))

[('Liming', 24, 63.9) ('Mike', 15, 67. ) ('Jan', 34, 45.8)] <class 'numpy.ndarray'>


In [69]:
personType2 = np.dtype([('name', 'U30'), ('age', 'i8'), ('weight', 'f8')])
bb = np.array([('Liming', 24, 63.9), ('Mike', 15, 67.), ('Jan', 34, 45.8)],
             dtype=personType2)
print(bb, type(bb))

[('Liming', 24, 63.9) ('Mike', 15, 67. ) ('Jan', 34, 45.8)] <class 'numpy.ndarray'>


## 4.9 数组的属性

- numpy.ndarray.ndim用于返回数组的维数（轴的个数）也称为秩，一维数组的秩为 1，二维数组的秩为 2，以此类推。
- numpy.ndarray.shape表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 ndim 属性(秩)。
- numpy.ndarray.size数组中所有元素的总量，相当于数组的shape中所有元素的乘积，例如矩阵的元素总量为行与列的乘积。
- numpy.ndarray.dtype ndarray 对象的元素类型。
- numpy.ndarray.itemsize以字节的形式返回数组中每一个元素的大小。

### 例

In [ ]:
#a = np.array([1, 2, 3, 4, 5])
#print(a.shape)   (5,)
#print(a.dtype)   int32
#print(a.size)   5
#print(a.ndim)   1
#print(a.itemsize)   4

#在ndarray中所有元素必须是同一类型，否则会自动向下转换，int->float->str。

#a = np.array([1, 2, 3, 4, 5])
# [1 2 3 4 5]
#b = np.array([1, 2, 3, 4, '5'])
# ['1' '2' '3' '4' '5']
#c = np.array([1, 2, 3, 4, 5.0])
# [1. 2. 3. 4. 5.]