# 1. 排序，搜索和计数

## 1.1 排序

- numpy.sort()

numpy.sort(a[, axis=-1, kind='quicksort', order=None]) Return a sorted copy of an array.
- axis：排序沿数组的（轴）方向，0表示按行，1表示按列，None表示展开来排序，默认为-1，表示沿最后的轴排序。
- kind：排序的算法，提供了快排'quicksort'、混排'mergesort'、堆排'heapsort'， 默认为‘quicksort'。
- order：排序的字段名，可指定字段排序，默认为None。

In [9]:
import numpy as np

np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

#设置seed（）里的数字就相当于设置了一个盛有随机数的“聚宝盆”，一个数字代表一个“聚宝盆”，当我们在seed（）的括号里设置相同的seed，
#“聚宝盆”就是一样的，那当然每次拿出的随机数就会相同（不要觉得就是从里面随机取数字，只要设置的seed相同取出地随机数就一样）。
#如果不设置seed，则每次会生成不同的随机数。（注：seed括号里的数值基本可以随便设置哦）

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]


In [10]:
y = np.sort(x)
print(y)

[[1.73 2.32 6.22 7.54 9.78]
 [5.17 6.93 8.25 9.28 9.76]
 [0.01 0.19 1.73 4.23 9.27]
 [0.88 4.29 4.97 7.32 7.99]
 [0.07 6.99 7.9  8.95 9.05]]


In [11]:
y = np.sort(x, axis=0)
print(y)

[[0.01 0.07 0.19 1.73 4.29]
 [2.32 4.23 0.88 1.73 6.22]
 [6.93 4.97 8.95 7.32 6.99]
 [7.99 5.17 9.28 7.9  8.25]
 [9.05 7.54 9.78 9.76 9.27]]


In [12]:
y = np.sort(x, axis=1)
print(y)

[[1.73 2.32 6.22 7.54 9.78]
 [5.17 6.93 8.25 9.28 9.76]
 [0.01 0.19 1.73 4.23 9.27]
 [0.88 4.29 4.97 7.32 7.99]
 [0.07 6.99 7.9  8.95 9.05]]


In [13]:
dt = np.dtype([('name', 'S10'), ('age', np.int)])
a = np.array([("Mike", 21), ("Nancy", 25), ("Bob", 17), ("Jane", 27)], dtype=dt)
b = np.sort(a, order='name')
print(b)


b = np.sort(a, order='age')
print(b)


[(b'Bob', 17) (b'Jane', 27) (b'Mike', 21) (b'Nancy', 25)]
[(b'Bob', 17) (b'Mike', 21) (b'Nancy', 25) (b'Jane', 27)]


- numpy.argsort()

numpy.argsort(a[, axis=-1, kind='quicksort', order=None]) Returns the indices that would sort an array.


In [14]:
np.random.seed(20200612)
x = np.random.randint(0, 10, 10)
print(x)

[6 1 8 5 5 4 1 2 9 1]


In [15]:
y = np.argsort(x)
print(y)

[1 6 9 7 5 3 4 0 2 8]


In [16]:
print(x[y])

[1 1 1 2 4 5 5 6 8 9]


In [18]:
y = np.argsort(-x)
print(y)

[8 2 0 3 4 5 7 1 6 9]


In [19]:
print(x[y])

[9 8 6 5 5 4 2 1 1 1]


In [20]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]


In [21]:
y = np.argsort(x)
print(y)

y = np.argsort(x, axis=0)
print(y)

y = np.argsort(x, axis=1)
print(y)

[[3 0 4 1 2]
 [1 0 4 2 3]
 [0 2 3 1 4]
 [2 4 1 3 0]
 [1 4 3 2 0]]
[[2 4 2 0 3]
 [0 2 3 2 0]
 [1 3 4 3 4]
 [3 1 1 4 1]
 [4 0 0 1 2]]
[[3 0 4 1 2]
 [1 0 4 2 3]
 [0 2 3 1 4]
 [2 4 1 3 0]
 [1 4 3 2 0]]


In [22]:
y = np.array([np.take(x[i], np.argsort(x[i])) for i in range(5)])  
print(y)

[[1.73 2.32 6.22 7.54 9.78]
 [5.17 6.93 8.25 9.28 9.76]
 [0.01 0.19 1.73 4.23 9.27]
 [0.88 4.29 4.97 7.32 7.99]
 [0.07 6.99 7.9  8.95 9.05]]


- numpy.lexsort()

numpy.lexsort(keys[, axis=-1]) Perform an indirect stable sort using a sequence of keys.（使用键序列执行间接稳定排序。）

- 给定多个可以在电子表格中解释为列的排序键，lexsort返回一个整数索引数组，该数组描述了按多个列排序的顺序。序列中的最后一个键用于主排序顺序，倒数第二个键用于辅助排序顺序，依此类推。keys参数必须是可以转换为相同形状的数组的对象序列。如果为keys参数提供了2D数组，则将其行解释为排序键，并根据最后一行，倒数第二行等进行排序。

In [23]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]


In [24]:
index = np.lexsort([x[:, 0]])
print(index)

y = x[index]
print(y)

index = np.lexsort([-1 * x[:, 0]])
print(index)

y = x[index]
print(y)

[2 0 1 3 4]
[[0.01 4.23 0.19 1.73 9.27]
 [2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
[4 3 1 0 2]
[[9.05 0.07 8.95 7.9  6.99]
 [7.99 4.97 0.88 7.32 4.29]
 [6.93 5.17 9.28 9.76 8.25]
 [2.32 7.54 9.78 1.73 6.22]
 [0.01 4.23 0.19 1.73 9.27]]


In [ ]:
x = np.array([1, 5, 1, 4, 3, 4, 4])
y = np.array([9, 4, 0, 4, 0, 2, 1])
a = np.lexsort([x])
b = np.lexsort([y])
print(a)
# [0 2 4 3 5 6 1]
print(x[a])
# [1 1 3 4 4 4 5]

print(b)
# [2 4 6 5 1 3 0]
print(y[b])
# [0 0 1 2 4 4 9]

z = np.lexsort([y, x])
print(z)
# [2 0 4 6 5 3 1]
print(x[z])
# [1 1 3 4 4 4 5]

z = np.lexsort([x, y])
print(z)
# [2 4 6 5 3 1 0]
print(y[z])
# [0 0 1 2 4 4 9]

- numpy.partition()

numpy.partition(a, kth, axis=-1, kind='introselect', order=None) Return a partitioned copy of an array.

Creates a copy of the array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array. All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.

In [25]:
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]


In [26]:
y = np.sort(x, axis=0)
print(y)

z = np.partition(x, kth=2, axis=0)
print(z)

[[ 3  5  3]
 [ 3 11  3]
 [ 8 15  4]
 [ 9 17 12]
 [16 22 16]
 [17 24 17]
 [18 25 21]
 [29 27 25]]
[[ 3  5  3]
 [ 3 11  3]
 [ 8 15  4]
 [ 9 22 21]
 [17 24 16]
 [18 17 25]
 [16 25 12]
 [29 27 17]]


In [28]:
z = np.partition(x, kth=2, axis=0)
print(z[2])

z = np.partition(x, kth=-3, axis=0)
print(z[-3])

[ 8 15  4]
[17 24 17]


- numpy.argpartition()

numpy.argpartition(a, kth, axis=-1, kind='introselect', order=None)

Perform an indirect partition along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in partitioned order.

In [29]:
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]


In [31]:
y = np.argsort(x, axis=0)
print(y)

z = np.argpartition(x, kth=2, axis=0)
print(z)

[[3 6 3]
 [4 2 4]
 [1 4 0]
 [0 5 6]
 [6 3 1]
 [2 1 7]
 [5 0 2]
 [7 7 5]]
[[3 6 3]
 [4 2 4]
 [1 4 0]
 [0 3 2]
 [2 1 1]
 [5 5 5]
 [6 0 6]
 [7 7 7]]


In [33]:
z = np.argpartition(x, kth=2, axis=0)
print(z[2])

z = np.argpartition(x, kth=-3, axis=0)
print(z[-3])

[1 4 0]
[2 1 7]


## 1.2 搜索

numpy.argmax()

numpy.argmax(a[, axis=None, out=None])Returns the indices of the maximum values along an axis.

In [34]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]


In [35]:
y = np.argmax(x)
print(y) 

y = np.argmax(x, axis=0)
print(y)

y = np.argmax(x, axis=1)
print(y)

2
[4 0 0 1 2]
[2 3 4 0 0]


numpy.argmin()

numpy.argmin(a[, axis=None, out=None])Returns the indices of the minimum values along an axis.

In [36]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]


In [37]:
y = np.argmin(x)
print(y)

y = np.argmin(x, axis=0)
print(y)

y = np.argmin(x, axis=1)
print(y)

10
[2 4 2 0 3]
[3 1 0 2 1]


numppy.nonzero()

numppy.nonzero(a) Return the indices of the elements that are non-zero.
，其值为非零元素的下标在对应轴上的值。

- 只有a中非零元素才会有索引值，那些零值元素没有索引值。
- 返回一个长度为a.ndim的元组（tuple），元组的每个元素都是一个整数数组（array）。
- 每一个array均是从一个维度上来描述其索引值。比如，如果a是一个二维数组，则tuple包含两个array，第一个array从行维度来描述索引值；第二个array从列维度来描述索引值。
- 该 np.transpose(np.nonzero(x)) 函数能够描述出每一个非零元素在不同维度的索引值。
- 通过a[nonzero(a)]得到所有a中的非零值。

In [38]:
x = np.array([0, 2, 3])
print(x)  
print(x.shape) 
print(x.ndim)  

y = np.nonzero(x)
print(y)  
print(np.array(y)) 
print(np.array(y).shape) 
print(np.array(y).ndim) 
print(np.transpose(y))

print(x[np.nonzero(x)])

[0 2 3]
(3,)
1
(array([1, 2]),)
[[1 2]]
(1, 2)
2
[[1]
 [2]]
[2 3]


In [39]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
print(x.shape)  
print(x.ndim)  

y = np.nonzero(x)
print(y)

print(np.array(y))

print(np.array(y).shape)
print(np.array(y).ndim) 

y = x[np.nonzero(x)]
print(y)  

y = np.transpose(np.nonzero(x))
print(y)

[[3 0 0]
 [0 4 0]
 [5 6 0]]
(3, 3)
2
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))
[[0 1 2 2]
 [0 1 0 1]]
(2, 4)
2
[3 4 5 6]
[[0 0]
 [1 1]
 [2 0]
 [2 1]]


In [40]:
x = np.array([[[0, 1], [1, 0]], [[0, 1], [1, 0]], [[0, 0], [1, 0]]])
print(x)
print(np.shape(x))  # (3, 2, 2)
print(x.ndim)  # 3

y = np.nonzero(x)
print(np.array(y))

print(np.array(y).shape)  
print(np.array(y).ndim) 
print(y)

print(x[np.nonzero(x)])

[[[0 1]
  [1 0]]

 [[0 1]
  [1 0]]

 [[0 0]
  [1 0]]]
(3, 2, 2)
3
[[0 0 1 1 2]
 [0 1 0 1 1]
 [1 0 1 0 0]]
(3, 5)
2
(array([0, 0, 1, 1, 2]), array([0, 1, 0, 1, 1]), array([1, 0, 1, 0, 0]))
[1 1 1 1 1]


In [41]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

y = x > 3
print(y)

y = np.nonzero(x > 3)
print(y)

y = x[np.nonzero(x > 3)]
print(y)

y = x[x > 3]
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [ True  True  True]
 [ True  True  True]]
(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))
[4 5 6 7 8 9]
[4 5 6 7 8 9]


- numpy.where()

numpy.where(condition, [x=None, y=None]) Return elements chosen from x or y depending on condition.

In [42]:
x = np.arange(10)
print(x)

y = np.where(x < 5, x, 10 * x)
print(y)

x = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
y = np.where(x < 4, x, -1)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]
[[ 0  1  2]
 [ 0  2 -1]
 [ 0  3 -1]]


只有condition，没有x和y，则输出满足条件 (即非0) 元素的坐标 (等价于numpy.nonzero)。这里的坐标以tuple的形式给出，通常原数组有多少维，输出的tuple中就包含几个数组，分别对应符合条件元素的各维坐标。

In [43]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.where(x > 5)
print(y)
print(x[y])

y = np.nonzero(x > 5)
print(y)
print(x[y])

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.where(x > 25)
print(y)
print(x[y])

y = np.nonzero(x > 25)
print(y)
print(x[y])

(array([5, 6, 7]),)
[6 7 8]
(array([5, 6, 7]),)
[6 7 8]
(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
[26 27 28 29 30 31 32 33 34 35]
(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
[26 27 28 29 30 31 32 33 34 35]


- numpy.searchsorted()

numpy.searchsorted(a, v[, side='left', sorter=None]) Find indices where elements should be inserted to maintain order.
- a：一维输入数组。当sorter参数为None的时候，a必须为升序数组；否则，sorter不能为空，存放a中元素的index，用于反映a数组的升序排列方式。
- v：插入a数组的值，可以为单个元素，list或者ndarray。
- side：查询方向，当为left时，将返回第一个符合条件的元素下标；当为right时，将返回最后一个符合条件的元素下标。
- sorter：一维数组存放a数组元素的 index，index 对应元素为升序。

In [ ]:
x = np.array([0, 1, 5, 9, 11, 18, 26, 33])
y = np.searchsorted(x, 15)
print(y)  # 5

y = np.searchsorted(x, 15, side='right')
print(y)  # 5

y = np.searchsorted(x, -1)
print(y)  # 0

y = np.searchsorted(x, -1, side='right')
print(y)  # 0

y = np.searchsorted(x, 35)
print(y)  # 8

y = np.searchsorted(x, 35, side='right')
print(y)  # 8

y = np.searchsorted(x, 11)
print(y)  # 4

y = np.searchsorted(x, 11, side='right')
print(y)  # 5

y = np.searchsorted(x, 0)
print(y)  # 0

y = np.searchsorted(x, 0, side='right')
print(y)  # 1

y = np.searchsorted(x, 33)
print(y)  # 7

y = np.searchsorted(x, 33, side='right')
print(y)  # 8

In [44]:
x = np.array([0, 1, 5, 9, 11, 18, 26, 33])
y = np.searchsorted(x, [-1, 0, 11, 15, 33, 35])
print(y)

y = np.searchsorted(x, [-1, 0, 11, 15, 33, 35], side='right')
print(y)

[0 0 4 5 7 8]
[0 1 5 5 8 8]


## 1.3 计数

- numpy.count_nonzero()

numpy.count_nonzero(a, axis=None) Counts the number of non-zero values in the array a.

In [45]:
x = np.count_nonzero(np.eye(4))
print(x) 

x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]])
print(x)

x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=0)
print(x)

x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=1)
print(x)

4
5
[1 1 1 1 1]
[2 3]
